name: expandable_menu
description: Expandable menu is an expandable menu with infinite horizontal item list with high customizable ability.
version: 0.0.4
homepage: https://github.com/mohammad-mohammady/expandable_menu

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
